# .github/workflows/pytest.yml

name: Run Pytest Suite

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: "Test on Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # All dependencies, including pytest, should be in requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pytest
        env:
          PYTHONPATH: code  # <-- CRITICAL FIX: Tells Python where your code is
        run: pytest
