# Workflow name 
name: Run Log Analyzer Tests

# Trigger this workflow on every push to any branch
on:
  push:
    branches:
      - '**'              # all branches 

jobs:
  pytest:
    runs-on: ubuntu-latest  

    # Test against multiple Python versions in parallel
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install pip, pytest, and any other requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run all tests
      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings --capture=tee-sys
